export const contactDiv = document.createElement('div');
contactDiv.id = 'contact'

const contactHeader = document.createElement('h1');
contactHeader.id = 'contacts-header'
contactHeader.textContent = "Contact Us"
contactDiv.appendChild(contactHeader);

const contactList = document.createElement('ul');
contactList.classList.add('contact-list');
contactDiv.appendChild(contactList);

const firstContactDiv = document.createElement('div');
firstContactDiv.classList.add('contact-item');
const firstContactName = document.createElement('h2');
firstContactName.classList.add('contact-name');
firstContactName.textContent = 'Whiskeyjack';
firstContactDiv.appendChild(firstContactName);
const firstContactDetails = document.createElement('ul');
firstContactDetails.classList.add('contact-details');
const firstContactTitle = document.createElement('li');
firstContactTitle.classList.add('contact-detail');
firstContactTitle.textContent = "Owner";
firstContactDetails.appendChild(firstContactTitle);
const firstContactNumber = document.createElement('li');
firstContactNumber.classList.add('contact-detail');
firstContactNumber.textContent = "555-555-5551";
firstContactDetails.appendChild(firstContactNumber);
const firstContactEmail = document.createElement('li');
firstContactEmail.classList.add('contact-detail');
firstContactEmail.textContent = 'whiskeyjack@bridgerburners.com';
firstContactDetails.appendChild(firstContactEmail);
firstContactDiv.appendChild(firstContactDetails);
contactDiv.appendChild(firstContactDiv);

const secondContactDiv = document.createElement('div');
secondContactDiv.classList.add('contact-item');
const secondContactName = document.createElement('h2');
secondContactName.classList.add('contact-name');
secondContactName.textContent = 'Fiddler';
secondContactDiv.appendChild(secondContactName);
const secondContactDetails = document.createElement('ul');
secondContactDetails.classList.add('contact-details');
const secondContactTitle = document.createElement('li');
secondContactTitle.classList.add('contact-detail');
secondContactTitle.textContent = "Musician";
secondContactDetails.appendChild(secondContactTitle);
const secondContactNumber = document.createElement('li');
secondContactNumber.classList.add('contact-detail');
secondContactNumber.textContent = "555-555-5552";
secondContactDetails.appendChild(secondContactNumber);
const secondContactEmail = document.createElement('li');
secondContactEmail.classList.add('contact-detail');
secondContactEmail.textContent = 'fiddler@bridgerburners.com';
secondContactDetails.appendChild(secondContactEmail);
secondContactDiv.appendChild(secondContactDetails);
contactDiv.appendChild(secondContactDiv);

const thirdContactDiv = document.createElement('div');
thirdContactDiv.classList.add('contact-item');
const thirdContactName = document.createElement('h2');
thirdContactName.classList.add('contact-name');
thirdContactName.textContent = 'Quick Ben';
thirdContactDiv.appendChild(thirdContactName);
const thirdContactDetails = document.createElement('ul');
thirdContactDetails.classList.add('contact-details');
const thirdContactTitle = document.createElement('li');
thirdContactTitle.classList.add('contact-detail');
thirdContactTitle.textContent = "Magical Chef";
thirdContactDetails.appendChild(thirdContactTitle);
const thirdContactNumber = document.createElement('li');
thirdContactNumber.classList.add('contact-detail');
thirdContactNumber.textContent = "555-555-5553";
thirdContactDetails.appendChild(thirdContactNumber);
const thirdContactEmail = document.createElement('li');
thirdContactEmail.classList.add('contact-detail');
thirdContactEmail.textContent = 'quickben@bridgerburners.com';
thirdContactDetails.appendChild(thirdContactEmail);
thirdContactDiv.appendChild(thirdContactDetails);
contactDiv.appendChild(thirdContactDiv);

const fourthContactDiv = document.createElement('div');
fourthContactDiv.classList.add('contact-item');
const fourthContactName = document.createElement('h2');
fourthContactName.classList.add('contact-name');
fourthContactName.textContent = 'Kalam';
fourthContactDiv.appendChild(fourthContactName);
const fourthContactDetails = document.createElement('ul');
fourthContactDetails.classList.add('contact-details');
const fourthContactTitle = document.createElement('li');
fourthContactTitle.classList.add('contact-detail');
fourthContactTitle.textContent = "Security";
fourthContactDetails.appendChild(fourthContactTitle);
const fourthContactNumber = document.createElement('li');
fourthContactNumber.classList.add('contact-detail');
fourthContactNumber.textContent = "555-555-5554";
fourthContactDetails.appendChild(fourthContactNumber);
const fourthContactEmail = document.createElement('li');
fourthContactEmail.classList.add('contact-detail');
fourthContactEmail.textContent = 'kalam@bridgerburners.com';
fourthContactDetails.appendChild(fourthContactEmail);
fourthContactDiv.appendChild(fourthContactDetails);
contactDiv.appendChild(fourthContactDiv);

const fifthContactDiv = document.createElement('div');
fifthContactDiv.classList.add('contact-item');
const fifthContactName = document.createElement('h2');
fifthContactName.classList.add('contact-name');
fifthContactName.textContent = 'Hedge';
fifthContactDiv.appendChild(fifthContactName);
const fifthContactDetails = document.createElement('ul');
fifthContactDetails.classList.add('contact-details');
const fifthContactTitle = document.createElement('li');
fifthContactTitle.classList.add('contact-detail');
fifthContactTitle.textContent = "Head of Staff";
fifthContactDetails.appendChild(fifthContactTitle);
const fifthContactNumber = document.createElement('li');
fifthContactNumber.classList.add('contact-detail');
fifthContactNumber.textContent = "555-555-5555";
fifthContactDetails.appendChild(fifthContactNumber);
const fifthContactEmail = document.createElement('li');
fifthContactEmail.classList.add('contact-detail');
fifthContactEmail.textContent = 'hedge@bridgerburners.com';
fifthContactDetails.appendChild(fifthContactEmail);
fifthContactDiv.appendChild(fifthContactDetails);
contactDiv.appendChild(fifthContactDiv);